# Generated by Django 5.0 on 2023-12-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
